name: deploy-manifests
on: 
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doct@v2
        with:
          token:  ...
      - run: doctl kunernetes cluster kubeconfig save ticketing  
      - run: kubectl apply -f infra/k8s
